name: Validate Using Latest Template Version
# -------------------------------------------------------------------------------------
# Overview
# -------------------------------------------------------------------------------------
# This workflow ensures that each template uses the (chronologically) latest release
# from the referenced model repository. The check also includes pre-releases.
# 
# -------------------------------------------------------------------------------------

on:
  push:
    paths:
      - 'templates.json'
    branches-ignore:
      - main
  pull_request:
    paths:
      - 'templates.json'
  workflow_dispatch:

jobs:
  validate-using-latest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Validate using latest version
        run: python .github/scripts/check_latest_version.py